### ISSUE TITLE
Audio.js在通过API服务端生成的时候会报错，

### ISSUE THREAD

**Issue by icedeng** [sbfkcel/towxml#54]
158行、163行的箭头函数写法不支持。

`
	fillIn = val => {
	       ^

SyntaxError: Unexpected token =
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
`

**Comment by sbfkcel** [comment]
发一下你的nodejs版本。和具体的代码。

**Comment by icedeng** [comment]
> 发一下你的nodejs版本。和具体的代码。

系统：macos 10.14.2
node：v11.3.0

**Comment by sbfkcel** [comment]
还有代码。

**Comment by icedeng** [comment]
改下lib/Audio.js，就解决问题了。
修复的代码如下：


        // 数字补位
        fillIn (val) {
            return `${val < 10 ? '0' : ''}${val}`;
        }

        // 格式化时间  
        formatTime( time) {
            let fillIn = this.fillIn,
                second = Math.floor(time % 60),
                minute = Math.floor(time / 60 % 60),
                hour = Math.floor(time / 60 / 60);
            return `${fillIn(hour)}:${fillIn(minute)}:${fillIn(second)}`;
        }

**Comment by sbfkcel** [comment]
大意了，感谢指出。谢谢。
